FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN    set -x \
    && apt update \
    && apt install -y --no-install-recommends \
        build-essential \
        python3 \
        python3-setuptools
